data:
  dwi_file: "data/subj_01/DTI-Mono_noPAT/DTI-Mono_noPAT.nii.gz"
  bval_file: "data/subj_01/DTI-Mono_noPAT/DTI-Mono_noPAT.bval"
  bvec_file: "data/subj_01/DTI-Mono_noPAT/DTI-Mono_noPAT.bvec"
  wm_mask_file: "data/subj_01/DTI-Mono_noPAT/DTI-Mono_noPAT_wm_mask.nii.gz"
  fa_file: "data/subj_01/DTI-Mono_noPAT/DTI-Mono_noPAT_FA.nii.gz"

atlas:
  brainnetome: "atlas/brainnetome/BN_Atlas_246_2mm.nii.gz"

output_dir: "output"